"""Membership: consuming the registry's grant and revocation events.

Corliss does not ask the registry who is a member — the registry tells it. On
each grant and revoke, HappyView Lua POSTs the event here and Corliss resolves
it into `MembershipCache`. That direction is deliberate: a pull would need
Corliss to authenticate to HappyView as itself, which is unsolved, and pushing
sidesteps it entirely.

The payload is an envelope around the registry record, verbatim:

    {"event": "grant",
     "did": "did:plc:…",
     "rkey": "did:plc:…:3lqx…",
     "authorDid": "did:plc:…",
     "record": {"status": "active", "grantedAt": "…", "tier": "level-2"}}

The envelope fields are exactly what `atproto.spaces.query` returns alongside
a record, so reconciliation reading the registry directly will fill the same
shape — one parser, not two, and no second schema to drift from the lexicon.

Two invariants that are easy to break and expensive to debug:

- **Never treat a `membership.grant` record found in the firehose index, or in
  someone's PDS, as authoritative.** The lexicon is published, so HappyView's
  indexer recognises records of that collection and anyone can publish one to
  their own repo. What makes a grant real is that it is *in the registry
  space*, written by an admin holding space write access. Membership must only
  ever arrive here through this module.
- **Order by the rkey's TID, never by the timestamps.** See `tid_of`.
"""

import re
from datetime import datetime, timezone as dt_timezone

from django.db import transaction

from corliss.models import MembershipCache

GRANT = "grant"
REVOKE = "revoke"
EVENTS = (GRANT, REVOKE)

# atproto DID shape. Matches the check the registry Lua applies before the DID
# becomes part of an rkey, so a value that was accepted there is accepted here.
_DID_RE = re.compile(r"^did:[a-z]+:[A-Za-z0-9._:%-]+$")

# A TID is 13 characters of base32-sortable. The alphabet is ordered so that
# lexicographic string comparison *is* chronological comparison, which is the
# entire reason `tid_of` can order events without parsing a timestamp.
_TID_RE = re.compile(r"^[234567abcdefghijklmnopqrstuvwxyz]{13}$")

MAX_DID_LEN = 255
MAX_TIER_LEN = 64


class PushError(ValueError):
    """A push payload that cannot be applied. The message reaches the caller."""


def tid_of(rkey):
    """Extract the ordering key from a registry rkey (`{memberDid}:{tid}`).

    This is the only thing events may be ordered by. The obvious alternative,
    `grantedAt`/`revokedAt`, is generated by the Lua with a second-resolution
    `os.date` format — so it cannot separate two events written in the same
    second, and a grant retried after a revocation could sort last and silently
    resurrect a revoked member. TIDs are monotonic per runtime and comparable
    across both collections, since one runtime issues them all.

    Split on the *last* colon: DIDs contain colons, TIDs never do.
    """
    _, sep, tid = rkey.rpartition(":")
    if not sep or not _TID_RE.match(tid):
        raise PushError(
            f"rkey does not end in a 13-character atproto TID: {rkey!r}. "
            "Ordering depends on that TID, so this is refused rather than "
            "applied in an order that cannot be trusted."
        )
    return tid


def _require_str(payload, key, *, max_len):
    value = payload.get(key)
    if not isinstance(value, str) or not value:
        raise PushError(f"missing or non-string {key!r}")
    if len(value) > max_len:
        raise PushError(f"{key!r} longer than {max_len} characters")
    return value


def _parse_timestamp(value, field):
    if not isinstance(value, str) or not value:
        raise PushError(f"missing or non-string {field!r}")
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        raise PushError(f"{field!r} is not an ISO-8601 datetime: {value!r}")
    # The registry writes UTC with a trailing Z. Anything naive is assumed UTC
    # rather than rejected, since the alternative is dropping a real event over
    # a formatting detail.
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt_timezone.utc)
    return parsed


def parse(payload):
    """Validate a push envelope, returning the fields needed to apply it.

    Raises `PushError` with a message intended to be readable in HappyView's
    script log, which is where a rejected push actually surfaces.
    """
    if not isinstance(payload, dict):
        raise PushError("payload must be a JSON object")

    event = payload.get("event")
    if event not in EVENTS:
        raise PushError(f"event must be one of {EVENTS!r}, got {event!r}")

    did = _require_str(payload, "did", max_len=MAX_DID_LEN)
    if not _DID_RE.match(did):
        raise PushError(f"not a valid DID: {did!r}")

    rkey = _require_str(payload, "rkey", max_len=600)
    tid = tid_of(rkey)

    # The rkey encodes its own subject, so a mismatch means the envelope and
    # the record disagree about who this is about. Refuse rather than guess.
    if not rkey.startswith(f"{did}:"):
        raise PushError(f"rkey {rkey!r} is not for did {did!r}")

    author_did = _require_str(payload, "authorDid", max_len=MAX_DID_LEN)
    if not _DID_RE.match(author_did):
        raise PushError(f"not a valid authorDid: {author_did!r}")

    record = payload.get("record")
    if not isinstance(record, dict):
        raise PushError("missing or non-object 'record'")

    if event == GRANT:
        tier = record.get("tier")
        if not isinstance(tier, str) or not tier:
            raise PushError("grant record has no 'tier'")
        if len(tier) > MAX_TIER_LEN:
            raise PushError(f"'tier' longer than {MAX_TIER_LEN} characters")
        # Shape only — deliberately NOT checked against a list of known tiers.
        # The registry already enforces the vocabulary at write time, and
        # duplicating it here would mean that adding a tier upstream makes
        # every push 400 while the Lua logs and returns success, so admins see
        # working approvals that never reach Corliss. An unknown tier flowing
        # through is the cheaper failure: Open WebUI ignores a group it does
        # not have.
        event_at = _parse_timestamp(record.get("grantedAt"), "record.grantedAt")
    else:
        tier = ""
        event_at = _parse_timestamp(record.get("revokedAt"), "record.revokedAt")

    return {
        "event": event,
        "did": did,
        "rkey": rkey,
        "tid": tid,
        "author_did": author_did,
        "tier": tier,
        "event_at": event_at,
    }


@transaction.atomic
def apply_event(parsed):
    """Apply a parsed push to the cache. Returns True if it changed anything.

    Returns False — not an error — when the event is not newer than what is
    already stored. Duplicates and out-of-order retries are normal for a
    best-effort push, and the Lua treats any non-2xx as a failure worth
    logging, so a replay must not look like one.
    """
    row = MembershipCache.objects.select_for_update().filter(
        did=parsed["did"]
    ).first()

    if row is not None and tid_of(row.last_rkey) >= parsed["tid"]:
        return False

    is_grant = parsed["event"] == GRANT
    MembershipCache.objects.update_or_create(
        did=parsed["did"],
        defaults={
            "active": is_grant,
            # A revocation carries no tier, so keep the last one for audit
            # rather than blanking it. Readers gate on `active`.
            "tier": parsed["tier"] if is_grant else (row.tier if row else ""),
            "last_rkey": parsed["rkey"],
            "last_event_at": parsed["event_at"],
            "author_did": parsed["author_did"],
        },
    )
    return True


def membership_for(user):
    """The cache row for a `User`, or None.

    The bridge the DID keying gives up and this hands back: callers holding a
    `User` get their membership in one indexed lookup without the cache having
    to own a foreign key. See `MembershipCache` for why it does not.
    """
    return MembershipCache.objects.filter(did=user.did).first()


def is_active_member(did):
    """GATE, as a single question: may this DID reach the cluster?

    Fails closed. No cached row means no known grant, which is a no — never a
    default-allow, and never a reason to go asking the registry inline.
    """
    return MembershipCache.objects.filter(did=did, active=True).exists()
