"""Membership: consuming the registry's grant and revocation events.

Corliss does not ask the registry who is a member — the registry tells it. On
each grant and revoke, HappyView Lua POSTs the event here and Corliss resolves
it into `MembershipCache`. That direction is deliberate: a pull would need
Corliss to authenticate to HappyView as itself, which is unsolved, and pushing
sidesteps it entirely.

The payload is an envelope around the registry record, verbatim:

    {"event": "grant",
     "did": "did:plc:…",
     "rkey": "did:plc:…:3lqx…",
     "authorDid": "did:plc:…",
     "record": {"status": "active", "grantedAt": "…", "tier": "level-2"}}

The envelope fields are exactly what `atproto.spaces.query` returns alongside
a record, so reconciliation reading the registry directly will fill the same
shape — one parser, not two, and no second schema to drift from the lexicon.

Two invariants that are easy to break and expensive to debug:

- **Never treat a `membership.grant` record found in the firehose index, or in
  someone's PDS, as authoritative.** The lexicon is published, so HappyView's
  indexer recognises records of that collection and anyone can publish one to
  their own repo. What makes a grant real is that it is *in the registry
  space*, written by an admin holding space write access. Membership must only
  ever arrive here through this module.
- **Order by the rkey's TID, never by the timestamps.** See `tid_of`.

Push is how the cache stays *fresh*; it is not how the cache is *built*. A
Corliss rebuilt from scratch has witnessed nothing, and no amount of pushing
repairs that, because the events it missed already happened. `reconcile` at the
bottom of this module is the other direction — reading the registry space and
re-deriving the whole cache from it — and `MembershipRegistry` is the thing that
does the reading. Together they are what makes an empty database recoverable.
See "Reconciliation" and "The registry, as something Corliss talks to".

The module also holds the **admin roster** — who is allowed to author a grant
in the first place. That belongs here rather than beside the atproto plumbing
because the rule it serves spans both halves: a grant is only real if its
author was a current admin when they wrote it. The roster arrives by a
different route from everything above — a public record read straight from the
service DID's repo, no push, no credential — which is precisely what makes it
usable when the cache is empty. See "The admin roster" below.

Last, and lowest in authority: **applications**, which are what someone writes
in their own PDS to ask. They confer nothing, and they are the only records
here that may be read from the firehose index. See "Applications" below for why
that does not contradict the first invariant above.
"""

import json
import logging
import re
from datetime import datetime, timedelta, timezone as dt_timezone

import requests
from cryptography.hazmat.primitives.asymmetric import ec
from jwt.algorithms import ECAlgorithm
from jwt.exceptions import InvalidKeyError
from django.conf import settings
from django.core.cache import cache
from django.db import transaction
from django.utils import timezone

from corliss import atproto, litellm, oidc
from corliss.models import MembershipCache, User

log = logging.getLogger(__name__)

GRANT = "grant"
REVOKE = "revoke"
EVENTS = (GRANT, REVOKE)

# atproto DID shape. Matches the check the registry Lua applies before the DID
# becomes part of an rkey, so a value that was accepted there is accepted here.
_DID_RE = re.compile(r"^did:[a-z]+:[A-Za-z0-9._:%-]+$")

# A TID is 13 characters of base32-sortable. The alphabet is ordered so that
# lexicographic string comparison *is* chronological comparison, which is the
# entire reason `tid_of` can order events without parsing a timestamp.
_TID_RE = re.compile(r"^[234567abcdefghijklmnopqrstuvwxyz]{13}$")

MAX_DID_LEN = 255
MAX_TIER_LEN = 64


class PushError(ValueError):
    """A push payload that cannot be applied. The message reaches the caller."""


def tid_of(rkey):
    """Extract the ordering key from a registry rkey (`{memberDid}:{tid}`).

    This is the only thing events may be ordered by. The obvious alternative,
    `grantedAt`/`revokedAt`, is generated by the Lua with a second-resolution
    `os.date` format — so it cannot separate two events written in the same
    second, and a grant retried after a revocation could sort last and silently
    resurrect a revoked member. TIDs are monotonic per runtime and comparable
    across both collections, since one runtime issues them all.

    Split on the *last* colon: DIDs contain colons, TIDs never do.
    """
    _, sep, tid = rkey.rpartition(":")
    if not sep or not _TID_RE.match(tid):
        raise PushError(
            f"rkey does not end in a 13-character atproto TID: {rkey!r}. "
            "Ordering depends on that TID, so this is refused rather than "
            "applied in an order that cannot be trusted."
        )
    return tid


def did_of(rkey):
    """Extract the subject DID from a registry rkey (`{memberDid}:{tid}`).

    The sibling of `tid_of`, and split the same way — on the *last* colon,
    because DIDs contain colons and TIDs never do.

    This exists because the registry's envelope carries no `did` field: the
    subject is the leading half of the rkey, and a copy alongside it could
    disagree with it. The push happens to send one (the Lua has it to hand),
    and `parse` cross-checks the two; a read straight from the space has only
    the rkey, so this is where that half comes from.
    """
    did, sep, _ = rkey.rpartition(":")
    if not sep or not did:
        raise PushError(f"rkey has no subject DID before its final colon: {rkey!r}")
    return did


def _require_str(payload, key, *, max_len):
    value = payload.get(key)
    if not isinstance(value, str) or not value:
        raise PushError(f"missing or non-string {key!r}")
    if len(value) > max_len:
        raise PushError(f"{key!r} longer than {max_len} characters")
    return value


def _parse_timestamp(value, field):
    if not isinstance(value, str) or not value:
        raise PushError(f"missing or non-string {field!r}")
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        raise PushError(f"{field!r} is not an ISO-8601 datetime: {value!r}")
    # The registry writes UTC with a trailing Z. Anything naive is assumed UTC
    # rather than rejected, since the alternative is dropping a real event over
    # a formatting detail.
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt_timezone.utc)
    return parsed


def parse(payload):
    """Validate a push envelope, returning the fields needed to apply it.

    Raises `PushError` with a message intended to be readable in HappyView's
    script log, which is where a rejected push actually surfaces.
    """
    if not isinstance(payload, dict):
        raise PushError("payload must be a JSON object")

    event = payload.get("event")
    if event not in EVENTS:
        raise PushError(f"event must be one of {EVENTS!r}, got {event!r}")

    did = _require_str(payload, "did", max_len=MAX_DID_LEN)
    if not _DID_RE.match(did):
        raise PushError(f"not a valid DID: {did!r}")

    rkey = _require_str(payload, "rkey", max_len=600)
    tid = tid_of(rkey)

    # The rkey encodes its own subject, so a mismatch means the envelope and
    # the record disagree about who this is about. Refuse rather than guess.
    if not rkey.startswith(f"{did}:"):
        raise PushError(f"rkey {rkey!r} is not for did {did!r}")

    author_did = _require_str(payload, "authorDid", max_len=MAX_DID_LEN)
    if not _DID_RE.match(author_did):
        raise PushError(f"not a valid authorDid: {author_did!r}")

    record = payload.get("record")
    if not isinstance(record, dict):
        raise PushError("missing or non-object 'record'")

    if event == GRANT:
        tier = record.get("tier")
        if not isinstance(tier, str) or not tier:
            raise PushError("grant record has no 'tier'")
        if len(tier) > MAX_TIER_LEN:
            raise PushError(f"'tier' longer than {MAX_TIER_LEN} characters")
        # Shape only — deliberately NOT checked against a list of known tiers.
        # The registry already enforces the vocabulary at write time, and
        # duplicating it here would mean that adding a tier upstream makes
        # every push 400 while the Lua logs and returns success, so admins see
        # working approvals that never reach Corliss. An unknown tier flowing
        # through is the cheaper failure: Open WebUI ignores a group it does
        # not have.
        event_at = _parse_timestamp(record.get("grantedAt"), "record.grantedAt")
    else:
        tier = ""
        event_at = _parse_timestamp(record.get("revokedAt"), "record.revokedAt")

    return {
        "event": event,
        "did": did,
        "rkey": rkey,
        "tid": tid,
        "author_did": author_did,
        "tier": tier,
        "event_at": event_at,
    }


@transaction.atomic
def apply_event(parsed):
    """Apply a parsed push to the cache. Returns True if it changed anything.

    Returns False — not an error — when the event is not newer than what is
    already stored. Duplicates and out-of-order retries are normal for a
    best-effort push, and the Lua treats any non-2xx as a failure worth
    logging, so a replay must not look like one.

    **This is also where revocation reaches the relying parties.** Both routes
    into the cache come through here — the registry's push, and `reconcile`'s
    pass 2 — so putting the notification here rather than in the two callers is
    what makes "revoked" mean "signed out of chat" no matter which one noticed.
    """
    row = MembershipCache.objects.select_for_update().filter(
        did=parsed["did"]
    ).first()

    if row is not None and tid_of(row.last_rkey) >= parsed["tid"]:
        return False

    is_grant = parsed["event"] == GRANT

    # Only a LIVE membership ending is worth telling anyone about: there was a
    # row, it said active, and this event ends it. The two cases this
    # deliberately excludes both look like revocations and are not:
    #
    # - **A revoke landing on no row at all.** That is what reconcile does on a
    #   rebuilt cluster — it replays every DID's winning event into an empty
    #   cache, and for anyone revoked in the past that winner is a revocation.
    #   Notifying there would fire a burst of POSTs at a relying party on the
    #   one path that has to work when little else does, to end sessions that
    #   ended long ago. The recovery path stays quiet.
    # - **A revoke landing on an already-revoked row.** A newer revocation of
    #   someone already revoked ends nothing.
    ends_live_membership = not is_grant and row is not None and row.active

    MembershipCache.objects.update_or_create(
        did=parsed["did"],
        defaults={
            "active": is_grant,
            # A revocation carries no tier, so keep the last one for audit
            # rather than blanking it. Readers gate on `active`.
            "tier": parsed["tier"] if is_grant else (row.tier if row else ""),
            "last_rkey": parsed["rkey"],
            "last_event_at": parsed["event_at"],
            "author_did": parsed["author_did"],
        },
    )

    # on_commit, not inline: this function is atomic, and an outbound HTTP call
    # has no business running inside an open transaction — it would hold row
    # locks across a network round trip, and it would fire for a write that then
    # rolled back. This way the notifications happen only if the change is
    # actually durable.
    did = parsed["did"]

    if ends_live_membership:
        # Two relying parties on one event, and neither may swallow the other:
        # chat holds a session that outlives the grant, and LiteLLM holds keys
        # that do the same. `_notify` keeps one failing from skipping the next.
        transaction.on_commit(lambda: _notify(oidc.notify_logout_for_did, did))
        transaction.on_commit(lambda: _notify(litellm.on_membership_revoked, did))
    elif is_grant:
        # **Provisioning before the first request is the point.** LiteLLM's
        # spend accounting silently no-ops for a user it has never heard of, so
        # a member who reaches it unprovisioned looks fine and accrues nothing.
        #
        # Unlike the revocation branch this deliberately fires on every applied
        # grant, including a reconcile replaying the whole log into a rebuilt
        # cluster: that is LiteLLM being re-provisioned from the record, which
        # is the same recovery the cache itself is getting. It is idempotent and
        # it never raises, which is what makes the burst safe.
        tier = parsed["tier"]
        transaction.on_commit(
            lambda: _notify(litellm.on_membership_granted, did, tier)
        )

    return True


def _notify(fn, *args):
    """Run one outbound notification, swallowing anything it throws.

    These run after commit, so there is nothing left to roll back and no caller
    left to tell. An exception here would surface as a 500 on the push — the
    registry logging a failure for a grant that succeeded — or abort the
    remaining notifications for the same event. Both are worse than a warning.
    """
    try:
        fn(*args)
    except Exception:
        # `getattr`, not `fn.__name__`: a callable without one (a partial, a
        # test double) would make the handler that exists to swallow errors
        # raise one of its own, which is the failure this whole function is here
        # to prevent.
        log.exception(
            "membership: notification %s failed", getattr(fn, "__name__", fn)
        )


def membership_for(user):
    """The cache row for a `User`, or None.

    The bridge the DID keying gives up and this hands back: callers holding a
    `User` get their membership in one indexed lookup without the cache having
    to own a foreign key. See `MembershipCache` for why it does not.
    """
    return MembershipCache.objects.filter(did=user.did).first()


def is_active_member(did):
    """Is there a live grant for this DID?

    Fails closed. No cached row means no known grant, which is a no — never a
    default-allow, and never a reason to go asking the registry inline.

    This is the *entitlement* half: it answers "has the registry granted this
    DID something", which is what a tier claim has to be derived from. It is
    deliberately **not** GATE on its own — see `may_enter`, which adds the
    roster so an admin can enter a Corliss whose cache is empty while still
    receiving nothing they were never granted.
    """
    return MembershipCache.objects.filter(did=did, active=True).exists()


# --- The admin roster ------------------------------------------------------
#
# The roster is what makes a grant legitimate: a grant is only real if its
# author was a current admin when they wrote it. That rule has the roster on
# one side and a grant on the other, which is why it lives here rather than in
# a module of its own — split across two files it would live in neither.
#
# Unlike grants, the roster needs no push and no credential. It is a public
# record in the service DID's repo, readable by anyone with
# `com.atproto.repo.getRecord`. Two consequences worth holding onto:
#
# - **ELEVATE never depends on the cache.** A Corliss rebuilt with an empty
#   database can still answer "is this DID an admin?" from a cold start. That
#   is the recovery path that makes closing GATE safe.
# - **Admin-ness is read, never stored.** Nothing here writes a Django flag.
#   Mapping cluster admin onto `is_superuser` would hand a roster edit the
#   power to bypass every permission check in Django and open the admin, where
#   this app's OIDC client config and session tables live.

ROSTER_COLLECTION = "network.sharedcomputer.admin.list"
ROSTER_RKEY = "self"  # the lexicon pins it: "key": "literal:self"

_ROSTER_CACHE_KEY = "corliss:roster"
# Cached in place of the record when there is no roster record at all, so the
# "never bootstrapped" answer is remembered as cheaply as a real one instead of
# re-reading the PDS on every login. A string rather than a sentinel object
# because it round-trips through any cache backend.
_ROSTER_ABSENT = "absent"
ROSTER_CACHE_TTL = 300

# A failed fetch is cached too, briefly. Without this an unreachable PDS adds
# the full request timeout to *every* login, since ELEVATE is asked on each one
# and a failure would never be remembered.
_ROSTER_FAILURE_KEY = "corliss:roster:failed"
ROSTER_FAILURE_TTL = 30


class RosterError(Exception):
    """The roster could not be fetched or is not shaped like a roster."""


class AdminEntry:
    """One admin's term on the roster: a DID, when it began, when it ended."""

    __slots__ = ("did", "added_at", "removed_at")

    def __init__(self, did, added_at, removed_at=None):
        self.did = did
        self.added_at = added_at
        self.removed_at = removed_at

    @property
    def is_current(self):
        return self.removed_at is None

    def covers(self, when):
        """Was this term in force at `when`? On or after added, before removed."""
        if when < self.added_at:
            return False
        return self.removed_at is None or when < self.removed_at

    def __repr__(self):
        state = "current" if self.is_current else f"removed {self.removed_at}"
        return f"AdminEntry({self.did}, {state})"


class Roster:
    """The parsed admin roster, answering the two questions anyone asks of it.

    A value object, not a model — the roster is not ours to store. It is
    fetched, asked, and discarded. Keeping it out of the database is what stops
    it becoming a second source of truth that can disagree with the record.

    A DID may hold more than one term (removed, later re-added), so every
    question is asked of *all* its entries, not the first one found.
    """

    def __init__(self, entries, malformed=(), exists=True):
        self.entries = list(entries)
        # DIDs whose entry could not be parsed. Not silently dropped: an
        # unreadable entry is an admin whose authority we cannot evaluate, and
        # reconciliation refuses to run against a roster it only half
        # understands rather than quietly ignoring their grants.
        self.malformed = list(malformed)
        # False only when the record does not exist yet — a network that has
        # never had a roster. Distinct from a roster that exists and lists
        # nobody, which is a deliberate state and fails closed like any other
        # empty roster. See `is_cluster_admin`.
        self.exists = exists

    @classmethod
    def from_record(cls, record):
        if not isinstance(record, dict):
            raise RosterError("roster record is not an object")
        admins = record.get("admins")
        if not isinstance(admins, list):
            raise RosterError("roster record has no 'admins' array")

        entries, malformed = [], []
        for raw in admins:
            if not isinstance(raw, dict):
                malformed.append(repr(raw)[:80])
                continue
            did = raw.get("did")
            if not isinstance(did, str) or not _DID_RE.match(did or ""):
                malformed.append(repr(did)[:80])
                continue
            try:
                added_at = _parse_timestamp(raw.get("addedAt"), "addedAt")
                removed = raw.get("removedAt")
                removed_at = (
                    _parse_timestamp(removed, "removedAt")
                    if removed is not None
                    else None
                )
            except PushError:
                # Both timestamps are what `covers` decides on, so an entry
                # with a bad one cannot be evaluated at all. It is malformed,
                # not "current".
                malformed.append(did)
                continue
            entries.append(AdminEntry(did, added_at, removed_at))

        return cls(entries, malformed)

    def is_current_admin(self, did):
        """ELEVATE: is this DID an admin *now*?"""
        return any(e.did == did and e.is_current for e in self.entries)

    def was_admin_at(self, did, when):
        """Was this DID a current admin at `when`?

        The question a consumer must ask of a grant's author, and deliberately
        not "are they an admin now". Removing an admin ends their authority
        going forward; it does not retroactively un-write what they approved.
        The other reading makes membership a function of the roster's current
        state, so removing one admin silently de-members everyone they ever
        approved with nothing in the event log to show for it.
        """
        return any(e.did == did and e.covers(when) for e in self.entries)

    @property
    def current_admins(self):
        return frozenset(e.did for e in self.entries if e.is_current)

    @property
    def ever_admins(self):
        """Every DID that has ever held authority, current or departed.

        The coarse filter for grant authors. `was_admin_at` is the exact one;
        this is what you want when discarding events from DIDs that were never
        admins at all, which is the only case that indicates forgery rather
        than history.
        """
        return frozenset(e.did for e in self.entries)

    def __len__(self):
        return len(self.entries)


def fetch_roster(*, refresh=False):
    """The current roster, cached briefly. Raises `RosterError` on failure.

    Cached because ELEVATE is asked on every login and the roster changes
    perhaps monthly. Never cached in the database — see `Roster`.
    """
    if not refresh:
        cached = cache.get(_ROSTER_CACHE_KEY)
        if cached == _ROSTER_ABSENT:
            return Roster([], exists=False)
        if cached is not None:
            return Roster.from_record(cached)
        failure = cache.get(_ROSTER_FAILURE_KEY)
        if failure is not None:
            raise RosterError(failure)

    service_did = settings.SCN_SERVICE_DID
    if not service_did:
        # Not an outage — an unconfigured deployment. Distinguish it, because
        # the operator fix is completely different from "the PDS is down".
        raise RosterError("SCN_SERVICE_DID is not configured")

    try:
        # `find_record`, not `get_record`, because "no roster record yet" and
        # "the PDS is down" must not answer the same way: the first is a network
        # nobody has bootstrapped and the second is an outage. A PDS reports
        # both with a 4xx and only the body tells them apart.
        record = atproto.find_record(service_did, ROSTER_COLLECTION, ROSTER_RKEY)
    except atproto.OAuthError as exc:
        cache.set(_ROSTER_FAILURE_KEY, str(exc), ROSTER_FAILURE_TTL)
        raise RosterError(str(exc)) from exc

    if record is None:
        cache.set(_ROSTER_CACHE_KEY, _ROSTER_ABSENT, ROSTER_CACHE_TTL)
        cache.delete(_ROSTER_FAILURE_KEY)
        return Roster([], exists=False)

    roster = Roster.from_record(record)
    # Cache the record, not the Roster: a plain dict survives any cache backend
    # and keeps a parser change from being invisible behind a stale object.
    cache.set(_ROSTER_CACHE_KEY, record, ROSTER_CACHE_TTL)
    cache.delete(_ROSTER_FAILURE_KEY)
    return roster


def is_cluster_admin(did):
    """ELEVATE, as a single question, safe to call from a request path.

    Swallows a roster failure into `False`: an unreachable PDS must not hand
    out admin, and must not 500 a login either. Callers that cannot tolerate a
    silent "no" — reconciliation, which would apply events unfiltered — call
    `fetch_roster` directly and let it raise.
    """
    if not did:
        return False
    # Local-development override, the ELEVATE counterpart to DEV_LOGIN_ENABLED.
    # Checked before the fetch because the case it exists for is precisely that
    # there is no roster record to fetch yet. DEBUG-gated here as well as
    # system-checked in corliss.apps — see settings.DEV_ADMIN_DIDS.
    if settings.DEBUG_FROM_ENV and did in settings.DEV_ADMIN_DIDS:
        return True
    try:
        roster = fetch_roster()
    except RosterError:
        return False
    if not roster.exists:
        # Bootstrap, mirroring the registry's own rule: with no roster record
        # anywhere, the service account is the sole admin so that the first one
        # can be written. It owns the repo the roster goes in, so this grants
        # nothing it could not already do by writing that record by hand — it
        # only lets it be done through `/manage/` instead.
        #
        # **An existing-but-empty roster still fails closed**, which is why this
        # asks `exists` rather than counting entries. Deliberately emptying the
        # roster is a decision; never having written one is not.
        return bool(settings.SCN_SERVICE_DID) and did == settings.SCN_SERVICE_DID
    return roster.is_current_admin(did)


def may_enter(did):
    """GATE, as a single question: may this DID use the cluster at all?

    Two ways in, and keeping them separate is the whole of the design:

    - an **active grant** in the cache, which is what membership means; or
    - a **current place on the admin roster**, which needs no cache row.

    The second clause is what makes closing this gate survivable. A Corliss
    rebuilt from nothing has an empty `MembershipCache` and therefore every
    member locked out — including every admin, if this asked only the cache.
    The roster is a public record read straight from the service DID's repo, so
    an admin can still get in and press the button that refills the cache.
    Gating on the cache alone would make the recovery path depend on the very
    thing being recovered.

    It buys that admin nothing else. Entitlements — the tier an id_token will
    carry — still come from `membership_for`, so an admin with no grant enters
    Corliss and receives nothing they were never given. GATE-for-Corliss and
    ENTITLE-for-Open-WebUI stay two questions with two answers, which is also
    how "admin does not imply member" is answered without inventing a grant.

    Reads the cache and the roster, and nothing else. **A cache miss must never
    trigger an inline registry fetch**: reconciliation is an operator action
    and a scheduled job, never a step in somebody's login.

    Order matters only for cost. Members are the common case and answer from
    one indexed row, so the roster — a cached read, and a network call when
    that cache is cold — is asked only when the cheap answer is no.
    """
    return bool(did) and (is_active_member(did) or is_cluster_admin(did))


# --- Editing the roster ----------------------------------------------------
#
# The roster is a record in the **service account's own repo**, and an atproto
# repo is writable only by its owner — there is no cross-repo grant to hand a
# person's session. So Corliss brokers: it verifies the actor is a current
# admin, then spends the service account's own stored session to make the edit.
# The actor's name goes into the entry (`addedBy` / `removedBy`), which is what
# keeps the record answerable for who decided what.
#
# **Why the roster stays where it is**, rather than moving somewhere Corliss
# could write it directly: three Lua procedures in scn-member-registry gate
# every registry write on this record, HappyView cannot read Corliss's
# database, and grants are verified against who was a current admin *at the
# grant's time* (`Roster.was_admin_at`). It is the registry's authorization
# mechanism, which Corliss reads — not Corliss's own notion of admin. Keeping
# it outside Corliss is also what leaves governance standing if Corliss is ever
# compromised.
#
# **Both halves of "make an admin" happen together.** The roster entry is the
# authority; `is_staff` is a local mirror of it so that "admin" means one thing
# in this app rather than two. The roster is written first: if that fails,
# nothing has changed and the caller gets an error naming the fix, rather than
# a half-admin who holds a Django flag the registry has never heard of.

ROSTER_MAX_ENTRIES = 500

# When the console starts saying the service session is worth a look. Not an
# expiry — nothing refuses on it. It exists so a lapse is noticed on a quiet
# Tuesday rather than while someone is trying to appoint an admin.
SERVICE_SESSION_STALE_DAYS = 30


# "Authenticate", never "sign in": the reader is already signed in as
# themselves and stays that way, and the wrong word makes an errand sound like
# being logged out.
SIGN_IN_AS_SERVICE = (
    "Use the lock on the console to authenticate the service account — nobody "
    "needs to be given a password to do it."
)


def _service_token(*, for_registry=False):
    """The service account's stored session, or a `RosterError` naming the fix.

    No new model and no new setting: the service account is a `User` like any
    other, and this is the row `views._store_tokens` wrote when it last signed
    in. What makes it usable for the roster is the scope that login asked for —
    see `views._scope_for`.

    **Two sessions expire independently, and only one of them is ours.** The
    stored PDS tokens are Corliss's and refresh themselves on use. The
    HappyView-registered session is HappyView's copy, and re-registering needs
    a key HappyView provisions for a fresh login handshake — so refreshing ours
    cannot revive theirs. `for_registry` asks for the second, which only
    `set_space_access` needs; the roster write is a plain PDS call and does not.

    Saying which one died is the whole point of the distinction: both failures
    look identical from the console and only one of them is worth signing in
    over.
    """
    from corliss.models import AtprotoToken

    service_did = settings.SCN_SERVICE_DID
    if not service_did:
        raise RosterError("SCN_SERVICE_DID is not configured")
    token = AtprotoToken.objects.filter(user__did=service_did).first()
    if token is None or not token.access_token:
        raise RosterError(
            f"there is no stored session for the service account. "
            f"{SIGN_IN_AS_SERVICE}"
        )
    if for_registry and not token.can_write_registry:
        raise RosterError(
            "the service account's session cannot reach the registry: it has "
            "PDS tokens but no registry session. " + SIGN_IN_AS_SERVICE
        )
    return token


def refresh_service_session():
    """Keep the service session alive. Returns a one-line status for the caller.

    The roster changes perhaps monthly, so without this the session would only
    ever be exercised at the moment somebody needs it — which is exactly when
    discovering it has expired is most expensive. Spending it on a schedule
    turns a lapse into something noticed by a cron job instead.

    Refreshing rotates the refresh token, which is the point: an atproto
    refresh token that is used stays alive, and one that is not eventually does
    not. **Only the PDS half.** HappyView's registered copy cannot be renewed
    from here — see `_service_token` — so this narrows the failure to something
    a sign-in fixes, it does not remove it.

    Never raises. A failed keep-alive must not fail the reconciliation it rides
    along with; the console's health line is where a human finds out.
    """
    try:
        token = _service_token()
    except RosterError as exc:
        return f"service session: {exc}"

    try:
        atproto.refresh_session(token)
    except atproto.OAuthError as exc:
        log.warning("service session refresh failed: %s", exc)
        return f"service session: could not refresh ({exc}). {SIGN_IN_AS_SERVICE}"
    return "service session: refreshed"


def service_session_status():
    """What `/manage/` shows about the session roster edits depend on.

    A dict, never an exception: this renders on a page that must still work
    when the answer is bad. `stale` is advisory only — nothing refuses on it —
    because the PDS is the authority on whether a token still works and a clock
    we do not own is not worth pre-empting.
    """
    from corliss.models import AtprotoToken

    service_did = settings.SCN_SERVICE_DID
    if not service_did:
        return {"configured": False}
    # A handle, because this renders on a page and a DID is not something to
    # show a person. Falls back to the DID only when resolution fails, which is
    # better than a blank where an account name belongs.
    handle = handles_for([service_did]).get(service_did, service_did)
    token = AtprotoToken.objects.filter(user__did=service_did).first()
    if token is None or not token.access_token:
        return {
            "configured": True,
            "did": service_did,
            "handle": handle,
            "present": False,
        }
    return {
        "configured": True,
        "did": service_did,
        "handle": handle,
        "present": True,
        "can_write_registry": token.can_write_registry,
        "registry_session_at": token.registry_session_at,
        "updated_at": token.updated_at,
        "stale": (
            token.registry_session_at is None
            or token.registry_session_at
            < timezone.now() - timedelta(days=SERVICE_SESSION_STALE_DAYS)
        ),
    }


def _write_roster(entries):
    """Persist `entries` as the roster record, as the service account.

    Uses `atproto.write_record`, which writes the *user's own* repo — which is
    exactly where the roster lives — and refreshes the access token once if the
    PDS says it is stale. Whole-record replace: the lexicon pins rkey `self`,
    so there is no partial update and no server-side merge.
    """
    token = _service_token()
    record = {
        "$type": ROSTER_COLLECTION,
        "admins": entries,
        "updatedAt": _now_iso(),
    }
    try:
        atproto.write_record(token.user, ROSTER_COLLECTION, ROSTER_RKEY, record)
    except atproto.OAuthError as exc:
        raise RosterError(f"could not write the roster: {exc}") from exc
    # The record we just wrote is the truth; the cached copy is now a lie, and
    # `/manage/` re-reads immediately after redirecting.
    cache.delete(_ROSTER_CACHE_KEY)
    cache.delete(_ROSTER_FAILURE_KEY)


def _now_iso():
    """Second-resolution UTC, matching what the registry Lua writes."""
    return datetime.now(dt_timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _raw_entries():
    """The roster record's `admins` array verbatim, for read-modify-write.

    Deliberately **not** `Roster.entries`: that is a parsed value object with
    the timestamps turned into datetimes and unreadable rows dropped. Writing
    it back would silently discard entries this version could not parse, which
    is exactly the data an older or newer writer put there. Round-tripping the
    raw dicts keeps a field we do not understand from being deleted by us.
    """
    service_did = settings.SCN_SERVICE_DID
    if not service_did:
        raise RosterError("SCN_SERVICE_DID is not configured")
    try:
        record = atproto.find_record(service_did, ROSTER_COLLECTION, ROSTER_RKEY)
    except atproto.OAuthError as exc:
        # Unreachable, which is not "no roster" — never let a PDS outage look
        # like a fresh network and tempt a caller into writing a genesis record
        # over a real one.
        raise RosterError(f"could not read the roster: {exc}") from exc
    if record is None:
        # Absent, not unreadable — a network failure raises out of
        # `find_record` instead. This is the fresh-network case.
        return None
    admins = record.get("admins")
    if not isinstance(admins, list):
        raise RosterError("roster record has no 'admins' array")
    return [e for e in admins if isinstance(e, dict)]


def _is_current(entry):
    return entry.get("removedAt") is None


def _set_staff(did, value):
    """Mirror roster membership onto the local `is_staff` flag.

    Best-effort and deliberately after the roster write: the roster is the
    authority, and `views._heal_staff_flag` re-derives this at every login, so
    a failure here self-corrects rather than needing a rollback.

    Superusers are left alone — Django's admin needs `is_staff` too, so
    clearing it would lock out an account somebody deliberately escalated.
    """
    User.objects.filter(did=did, is_superuser=False).update(is_staff=value)


def ensure_user(did, handle=None):
    """The local row for a DID, created if this is the first we have seen of it.

    Called when a grant is written, so a member has a row — and therefore a
    readable handle — from the moment they are admitted rather than from their
    first sign-in. Before this, someone invited and not yet arrived had nothing
    but a DID to render, which is not something to show a person.

    `MembershipCache` still has no foreign key to `User` and must not grow one:
    this pre-creates a row, it does not couple the two. `views._upsert_member`
    refreshes the username from the PDS at first login, so a handle that has
    changed in the meantime corrects itself.
    """
    user, created = User.objects.get_or_create(
        did=did, defaults={"username": handle or handles_for([did]).get(did, did)}
    )
    if created:
        # ATProto OAuth only — never a password, the same as every other row
        # this app makes.
        user.set_unusable_password()
        user.save(update_fields=["password"])
    elif handle and user.username != handle:
        user.username = handle
        user.save(update_fields=["username"])
    return user


def appoint_admin(actor_did, subject_did):
    """Make `subject_did` a cluster admin. Returns a note for the caller.

    Both halves, in the order that fails safely: the roster record first, then
    the local `is_staff` mirror, then registry space write access — which is
    what actually lets the new admin author a grant, and is reported rather
    than raised when it fails (see below).
    """
    _require_did(subject_did)
    if not is_active_member(subject_did):
        # Admins are members. The console only offers the button on member rows,
        # but the rule lives here so the CLI and any later caller obey it too.
        # On a fresh network the service account admits the first member and
        # then appoints them, so this needs no bootstrap exception.
        raise RosterError(
            "only a current member can be made an admin — admit them first"
        )
    entries = _raw_entries()
    if entries is None:
        # Genesis. Nothing has ever been written, and the only actor who can
        # reach this state is the service account (see `is_cluster_admin`'s
        # bootstrap clause), so seed it onto its own roster: it must be a
        # current admin to pass GATE and sign in again after this.
        entries = [
            {
                "did": settings.SCN_SERVICE_DID,
                "addedAt": _now_iso(),
                "addedBy": actor_did,
            }
        ]
    if any(e.get("did") == subject_did and _is_current(e) for e in entries):
        raise RosterError(f"already a current admin: {subject_did}")
    if len(entries) >= ROSTER_MAX_ENTRIES:
        # The whole record is rewritten on every edit and a PDS caps record
        # size. Refusing with a number beats a putRecord failure nobody can read.
        raise RosterError(
            f"the roster already holds {len(entries)} entries "
            f"(limit {ROSTER_MAX_ENTRIES})"
        )

    # Appended, never merged into a previous term for the same DID: a re-added
    # admin gets a second entry, so the record still says when each term began
    # and ended. `Roster.covers` is written to expect exactly that.
    entries.append(
        {"did": subject_did, "addedAt": _now_iso(), "addedBy": actor_did}
    )
    _write_roster(entries)
    # Ensured rather than assumed: the console's table reads admin status off
    # `is_staff`, so a member with no local row would appear not to be an admin
    # however correct the roster is.
    ensure_user(subject_did)
    _set_staff(subject_did, True)
    return _sync_space_access(subject_did, "write")


def dismiss_admin(actor_did, subject_did):
    """End `subject_did`'s admin authority. Returns a note for the caller.

    **Ends it going forward and no further.** Grants they authored while
    current stay valid — `Roster.was_admin_at` asks the question at the event's
    timestamp — and nothing here touches `MembershipCache`. Un-granting a
    member is always an explicit revocation, never a side effect of a roster
    edit, or removing one admin would silently de-member everyone they ever
    approved with nothing in the event log to show for it.
    """
    _require_did(subject_did)
    if subject_did == settings.SCN_SERVICE_DID:
        # It writes this record. Off the roster it fails GATE, cannot sign in
        # to refresh the session that performs the write, and the only way back
        # is editing the repo by hand.
        raise RosterError(
            "the service account cannot be removed from the roster: it is what "
            "writes the roster."
        )
    entries = _raw_entries()
    if entries is None:
        raise RosterError("no roster record exists yet")
    current = [e for e in entries if _is_current(e)]
    if not any(e.get("did") == subject_did for e in current):
        raise RosterError(f"not a current admin: {subject_did}")
    if len(current) <= 1:
        # An existing-but-empty roster fails closed everywhere and the
        # registry's BOOTSTRAP_ADMIN_DID escape only applies when the record is
        # *absent*, so this would end every approve and revoke with no way back
        # except editing the service account's repo by hand.
        raise RosterError(
            "refusing to remove the last admin: nobody could approve members, "
            "and nobody could add an admin back."
        )

    stamped = _now_iso()
    for entry in entries:
        if entry.get("did") == subject_did and _is_current(entry):
            # Stamped, never deleted. The record is the history of who held
            # authority and when, and `was_admin_at` needs the departed terms.
            entry["removedAt"] = stamped
            entry["removedBy"] = actor_did
    _write_roster(entries)
    _set_staff(subject_did, False)
    return _sync_space_access(subject_did, "none")


def _sync_space_access(did, access):
    """Match registry space write access to the roster. Returns a note or "".

    Space membership is what makes a grant authoritative at the registry, so an
    admin without it is on the roster and still cannot approve anyone.

    **Reported, never raised.** The roster write already succeeded and is the
    authority; failing the whole call here would tell the caller nothing
    happened when something did. Both the Lua and the roster edit are
    idempotent, so re-running the appointment completes it — which is what the
    returned note asks the operator to do.
    """
    registry = MembershipRegistry.from_settings()
    try:
        registry.set_space_access(
            _service_token(for_registry=True), did, access
        )
    except (RegistryError, RosterError) as exc:
        log.warning("space access sync for %s → %s failed: %s", did, access, exc)
        if access == "write":
            return (
                f"The roster was updated, but registry space access was not "
                f"({exc}). They are an admin and can reach the console; they "
                f"cannot approve anyone until this half lands. Run the same "
                f"action again to finish it."
            )
        return (
            f"The roster was updated, but registry space access was not "
            f"({exc}). Their authority has ended, but they keep space write "
            f"access until this half lands. Run the same action again."
        )
    return ""


def _require_did(did):
    if not did or not _DID_RE.match(did) or len(did) > MAX_DID_LEN:
        raise RosterError(f"not a DID: {did!r}")


# --- Handles, for display only ---------------------------------------------
#
# A DID is what this app trusts and keys on; a handle is what a person reads.
# The console shows handles, so this resolves them — and nothing else may.
# Never key on, compare, or store what comes out of here: handles are mutable
# and reassignable, so a resolved handle is a label with a timestamp on it, not
# an identity. That is also why a failure is not an error: an unresolvable DID
# renders as the DID, which is still the true answer to "who is this".

_HANDLE_CACHE_PREFIX = "corliss:handle:"
HANDLE_CACHE_TTL = 3600
# A DID that does not resolve is remembered too, briefly — otherwise every
# render of the console pays the full request timeout for it again.
HANDLE_FAILURE_TTL = 120


def handles_for(dids):
    """Map DIDs to handles for display. Missing entries mean "show the DID".

    Two sources, cheapest first: members who have signed in already carry their
    handle on the `User` row, refreshed at each login, so the common case costs
    one query. Anyone else — an admin who has never logged into this Corliss —
    is looked up in their DID document, which is public and needs no
    credential. Both are cached; the DID document lookup is a network call per
    unknown DID and the console would otherwise repeat it on every render.
    """
    wanted = {did for did in dids if did}
    resolved, unresolved = {}, set()

    for did in wanted:
        cached = cache.get(f"{_HANDLE_CACHE_PREFIX}{did}")
        if cached is None:
            unresolved.add(did)
        elif cached:
            resolved[did] = cached

    if not unresolved:
        return resolved

    for did, username in User.objects.filter(did__in=unresolved).values_list(
        "did", "username"
    ):
        if username:
            resolved[did] = username
            unresolved.discard(did)
            cache.set(f"{_HANDLE_CACHE_PREFIX}{did}", username, HANDLE_CACHE_TTL)

    for did in unresolved:
        handle = None
        try:
            handle = atproto.handle_from_doc(atproto.fetch_did_document(did))
        except atproto.OAuthError:
            # Unreachable directory, or a DID method we cannot read. Display
            # only — the page shows the DID and carries on.
            pass
        if handle:
            resolved[did] = handle
        cache.set(
            f"{_HANDLE_CACHE_PREFIX}{did}",
            handle or "",
            HANDLE_CACHE_TTL if handle else HANDLE_FAILURE_TTL,
        )

    return resolved

# --- Reconciliation --------------------------------------------------------
#
# Re-deriving the whole cache from the registry, rather than waiting to be told
# about the next change. This exists for one failure the push cannot reach:
# **a rebuilt Corliss has witnessed nothing.** Flash the cluster, run the
# provisioning script, and `MembershipCache` is empty — every grant ever made
# is still in the registry, and none of it is here. Nothing will push those
# events again, because they already happened. So reconciliation is not a
# freshness mechanism that the push happens not to cover; it is the only route
# by which membership can *re-enter* a Corliss that has lost it, and therefore
# a prerequisite for gating anything on the cache at all.
#
# Three rules this code exists to enforce, each of which has a plausible-looking
# implementation that gets it wrong:
#
# - **The events must come from the registry SPACE.** The grant lexicon is
#   published, so HappyView's indexer recognises `membership.grant` records
#   wherever it finds them and anyone can write one into their own PDS. A
#   caller must hand this function the result of an `atproto.spaces.query`
#   against the registry space — never a firehose index query, never a repo
#   read. Nothing downstream can tell the difference, which is exactly why it
#   is stated here.
# - **Authority is asked at the moment of the event, not now.** See
#   `Roster.was_admin_at`.
# - **`unresolved` is a blocker, not a warning.** A DID whose winning event
#   cannot be parsed is a member missing from the cache. Reporting it as a
#   footnote and carrying on is how a real member ends up locked out by a gate
#   that was told everything was fine.


class ReconcileError(Exception):
    """Reconciliation refused to run — the inputs cannot be trusted at all.

    Distinct from any per-event problem, which is reported rather than raised.
    This is "do not believe the report I would have produced".
    """


class ReconcileReport:
    """What a reconciliation run did, and whether it can claim to be complete.

    The two failure lists matter more than the two success lists. `applied` and
    `unchanged` are bookkeeping; `unresolved` and `orphans` are the reasons an
    operator must not yet close the gate.
    """

    __slots__ = ("applied", "unchanged", "unresolved", "orphans")

    def __init__(self):
        # DIDs whose winning event changed the cache.
        self.applied = []
        # DIDs whose winning event the cache already reflected. The expected
        # steady state — a healthy re-run is all of these.
        self.unchanged = []
        # {"did", "rkey", "error"} — the winning event could not be parsed, so
        # this DID's membership is unknown and its cache row (if any) is stale.
        self.unresolved = []
        # {"did", "active", "tier", "author_did"} — a cache row with no
        # admin-authored registry event behind it.
        self.orphans = []

    @property
    def is_complete(self):
        """Did this run account for every member and every cache row?

        The single question the gate's proof obligation asks. Deliberately not
        "did it apply cleanly": a run can apply every event it understood and
        still be incomplete, which is the case worth refusing on.
        """
        return not self.unresolved and not self.orphans

    def __repr__(self):
        return (
            f"ReconcileReport(applied={len(self.applied)}, "
            f"unchanged={len(self.unchanged)}, "
            f"unresolved={len(self.unresolved)}, "
            f"orphans={len(self.orphans)})"
        )


def _preview(event):
    """Read only what resolution needs, without committing to `parse`.

    Ordering and the authority check both have to happen *before* full parsing,
    because `parse` rejects the tierless pre-E0 grants that are permanently in
    the registry log — and one of those may still be a member's latest event.
    Dropping it at the door would silently de-member someone; letting it take
    part in ordering and failing on it later reports them as unresolved, which
    is the truth.

    Returns `(did, author_did, tid, when)`. Raises `PushError` if the envelope
    cannot even be read that far.
    """
    if not isinstance(event, dict):
        raise PushError("event must be a JSON object")

    kind = event.get("event")
    if kind not in EVENTS:
        raise PushError(f"event must be one of {EVENTS!r}, got {kind!r}")

    did = _require_str(event, "did", max_len=MAX_DID_LEN)
    author_did = _require_str(event, "authorDid", max_len=MAX_DID_LEN)
    tid = tid_of(_require_str(event, "rkey", max_len=600))

    record = event.get("record")
    if not isinstance(record, dict):
        raise PushError("missing or non-object 'record'")

    field = "grantedAt" if kind == GRANT else "revokedAt"
    return did, author_did, tid, _parse_timestamp(record.get(field), f"record.{field}")


def _would_change(parsed):
    """`apply_event`'s decision, asked without taking the write.

    Mirrors the guard in `apply_event` rather than sharing it: that one runs
    inside `select_for_update`, and a dry run has no business locking rows it
    has already promised not to touch. Keep the two comparisons identical.

    Routing dry runs through here rather than `apply_event` also keeps them
    silent on the wire: `apply_event` is what notifies relying parties of a
    revocation, so a preview that reached it would sign people out of chat to
    show an operator what a run *would* do. Correct by construction today —
    stated so it survives someone tidying the two paths back together.
    """
    row = MembershipCache.objects.filter(did=parsed["did"]).first()
    return row is None or tid_of(row.last_rkey) < parsed["tid"]


def reconcile(events, roster, *, dry_run=False):
    """Re-derive the cache from registry events. Returns a `ReconcileReport`.

    `events` must be push-shaped envelopes read from the **registry space** —
    see the section comment above; this function cannot verify that for itself.
    `roster` is a `Roster`, not a set of DIDs: the authority question is asked
    per event at that event's own timestamp, which needs the terms, not the
    names. Callers build it with `fetch_roster()`, which raises rather than
    failing closed the way `is_cluster_admin` does — reconciling against a
    roster that could not be fetched would discard every event as unauthorised.

    With `dry_run`, nothing is written and the report reads identically, so an
    operator can see what a run would do before it does it.
    """
    if roster.malformed:
        # Promised in `Roster`: an entry we cannot parse is an admin whose
        # authority cannot be evaluated, so every grant they ever wrote would
        # be silently discarded as unauthorised. That is a de-membering, and it
        # would be invisible in the report. Refuse the whole run instead.
        raise ReconcileError(
            f"roster has {len(roster.malformed)} unparseable "
            f"entr{'y' if len(roster.malformed) == 1 else 'ies'} "
            f"({', '.join(roster.malformed)}) — refusing to evaluate authority "
            "against a roster that is only half understood."
        )

    report = ReconcileReport()
    winners = {}  # did -> (tid, event)
    # DIDs the registry accounts for: those with an admin-authored event, plus
    # those with an event we could not read. Anything else with a cache row is
    # an orphan — so a DID only ever earns a place here by surviving the
    # authority check below.
    seen = set()

    # Pass 1: filter by authority, then order. The order of those two steps is
    # load-bearing — resolving first would let an event forged with a later TID
    # suppress the real grant underneath it, and the forgery would then be
    # discarded, leaving the member with no winning event at all.
    for event in events:
        try:
            did, author_did, tid, when = _preview(event)
        except PushError as exc:
            # Cannot be ordered and cannot be judged. Not dropped: an event we
            # cannot read might have been the winner, so the DID it names can
            # no longer be claimed as complete. A malformed record in the space
            # will pin this open until an admin fixes it, which is the correct
            # amount of noise for an admin-write-only collection.
            raw = event if isinstance(event, dict) else {}
            raw_did = raw.get("did") if isinstance(raw.get("did"), str) else None
            report.unresolved.append(
                {"did": raw_did, "rkey": raw.get("rkey"), "error": str(exc)}
            )
            if raw_did:
                seen.add(raw_did)
            continue

        if not roster.was_admin_at(author_did, when):
            # Either a forgery, or an admin acting outside their term. Both are
            # non-events, and the DID stays *unaccounted for* — deliberately
            # not added to `seen`, or a row planted by a stolen token would be
            # excused by the very event that proves it was planted.
            continue

        seen.add(did)
        current = winners.get(did)
        if current is None or tid > current[0]:
            winners[did] = (tid, event)

    # Pass 2: parse only the winner, never the whole log.
    for did in sorted(winners):
        event = winners[did][1]
        try:
            parsed = parse(event)
        except PushError as exc:
            # The tierless pre-E0 grants land here when they are somebody's
            # latest event. Never repaired with a default tier: inventing one
            # hands out an entitlement the registry never granted.
            report.unresolved.append(
                {"did": did, "rkey": event.get("rkey"), "error": str(exc)}
            )
            continue

        changed = _would_change(parsed) if dry_run else apply_event(parsed)
        (report.applied if changed else report.unchanged).append(did)

    # Pass 3: cache rows the registry does not account for. A leaked push token
    # produces exactly this — a row that no admin ever authored in the space —
    # and so does a row whose only events came from a DID that was never an
    # admin, since those never reached `winners`. Reported, never pruned here:
    # deleting membership is an operator's decision, not a library's.
    for row in MembershipCache.objects.exclude(did__in=sorted(seen)):
        report.orphans.append(
            {
                "did": row.did,
                "active": row.active,
                "tier": row.tier,
                "author_did": row.author_did,
            }
        )

    return report


# --- Applications ----------------------------------------------------------
#
# Someone asking to join. An application is a `membership.request` record with
# rkey `self` in the **applicant's own PDS** — one per account — picked up by
# HappyView's firehose indexer and handed back by the `listRequests` query.
#
# **This is the one collection Corliss may read from the index, and the
# exception proves the rule rather than weakening it.** The standing invariant
# a few sections up — never treat a `membership.grant` found in the firehose or
# in a PDS as authoritative — exists because the grant lexicon is published, so
# anyone can write a record of that shape into their own repo and have it
# indexed. That argument does not apply here for the reason it is fatal there:
# an application is *self-authored by definition*. It asserts only "I would
# like in", carries no authority, and is worth precisely nothing until an admin
# writes a grant into the registry space. Reading one from the index is
# therefore reading exactly what it claims to be.
#
# Two consequences worth stating, since both are easy to get backwards:
#
# - **An application is never evidence of membership.** Whether an applicant is
#   a member is answered by `MembershipCache`, and nowhere else on this page.
# - **The record is world-readable, so it holds no contact details** — by
#   design, upstream. Do not add a field here expecting one.


class Application:
    """One membership application: who asked, when, and what they said.

    A value object like `AdminEntry` — parsed, displayed, discarded. Nothing
    here is stored: the applicant's PDS holds the record and the registry
    indexes it, so a copy in Corliss could only ever be a third version to
    disagree with the other two.
    """

    __slots__ = ("did", "created_at", "note")

    def __init__(self, did, created_at, note=""):
        self.did = did
        self.created_at = created_at
        self.note = note

    def __repr__(self):
        return f"Application({self.did}, {self.created_at})"


def did_from_uri(uri):
    """The repo DID out of an `at://<did>/<collection>/<rkey>` record uri.

    Raises `PushError` — the module's "one record is malformed" error — on
    anything that is not one, including a leading segment that is not a DID.
    The registry's applications carry no `did` field; this is the only place
    the subject comes from, so a bad uri means an applicant we cannot name.
    """
    if not isinstance(uri, str) or not uri.startswith("at://"):
        raise PushError(f"not a record uri: {uri!r}")
    did = uri[len("at://"):].split("/", 1)[0]
    if not _DID_RE.match(did) or len(did) > MAX_DID_LEN:
        raise PushError(f"record uri does not start with a DID: {uri!r}")
    return did


class ApplicationList:
    """What one read of the applications returned, including what it could not
    read.

    The unreadable rows are carried rather than dropped for the same reason
    `Roster.malformed` is: an application that cannot be parsed is a person who
    asked and would otherwise vanish silently from the queue. The console shows
    the count, so a malformed record is visible as a number rather than as an
    absence nobody can see.
    """

    __slots__ = ("applications", "unreadable", "truncated")

    def __init__(self, applications, unreadable=0, truncated=False):
        self.applications = list(applications)
        self.unreadable = unreadable
        # True when the cursor was still running when the page cap was hit, so
        # the list is a prefix rather than the whole of it.
        self.truncated = truncated

    def __len__(self):
        return len(self.applications)

    def __iter__(self):
        return iter(self.applications)


# --- Applying, and reading your own application back -----------------------
#
# The two halves above read *other people's* applications out of the index, for
# an admin. These read and write the caller's own, straight from and to their
# PDS, and the difference is not stylistic:
#
# - **The index lags the write.** An applicant who is shown their own state
#   from `listRequests` watches the button do nothing for however long the
#   firehose takes. Their PDS answers the instant the write lands, so that is
#   where their own state comes from — always.
# - **The write goes to their repo and nowhere else.** Corliss holds their PDS
#   tokens, so it writes the record directly; it does not need a HappyView
#   session, and there is no path here that could write into the registry
#   space. A non-member could not write there in any case.
#
# And the constraint that outranks both: **applying confers nothing.** Nothing
# below touches `MembershipCache`, and a record here is never evidence of
# membership. It says "I would like in", and only a grant answers it.

REQUEST_COLLECTION = "network.sharedcomputer.membership.request"
REQUEST_RKEY = "self"  # the lexicon pins it: "key": "literal:self"

# The note's limits, from the lexicon: maxGraphemes 300, maxLength 1000 (UTF-8
# bytes). Graphemes are counted as code points here — never fewer than
# graphemes, so the check is conservative in the safe direction and needs no
# grapheme-segmentation dependency for a field this size.
NOTE_MAX_CHARS = 300
NOTE_MAX_BYTES = 1000

_APPLICATION_CACHE_PREFIX = "corliss:application:"
# Short, because the state changes under a member's feet the moment an admin
# approves them and the nav renders it on every page. Long enough that browsing
# does not become one PDS round trip per click.
APPLICATION_CACHE_TTL = 120
APPLICATION_FAILURE_TTL = 30

# What `my_application` caches to mean "asked, and there is no record" — a
# sentinel rather than `None`, since `cache.get` uses `None` for a miss.
_NO_APPLICATION = "none"


class ApplicationError(Exception):
    """The application could not be written, or the note was unacceptable.

    One class for both because they reach the member the same way: as a
    sentence on the home page explaining why the button did not work.
    """


def _application_cache_key(did):
    return _APPLICATION_CACHE_PREFIX + did


def validate_note(note):
    """The note, trimmed — or raise `ApplicationError` saying what is wrong.

    Checked here rather than left to the PDS because the PDS's refusal is a
    lexicon validation error the member cannot act on, and because the note is
    **public**: a member who is told the limit before writing is less likely to
    put something in it they would rather not publish.
    """
    note = (note or "").strip()
    if len(note) > NOTE_MAX_CHARS:
        raise ApplicationError(
            f"That note is {len(note)} characters; the limit is "
            f"{NOTE_MAX_CHARS}."
        )
    if len(note.encode("utf-8")) > NOTE_MAX_BYTES:
        raise ApplicationError("That note is too long.")
    return note


def my_application(did, *, refresh=False):
    """This DID's own application, read from their PDS. `None` if none.

    Cached the way `fetch_roster` is, and for the same reason: the nav asks on
    every render (`User.has_pending_application`) and the answer changes rarely.
    The record dict is what goes in the cache, not a parsed object, so a cache
    that outlives a parser change cannot hide it.

    Raises `ApplicationError` when the PDS could not be reached. That is a third
    answer, distinct from "has applied" and "has not", and callers that render a
    state to a member must not collapse it into either — telling someone they
    have not applied because their PDS blinked would invite a second record over
    the first.
    """
    key = _application_cache_key(did)
    if not refresh:
        cached = cache.get(key)
        if cached is not None:
            return None if cached == _NO_APPLICATION else cached

    try:
        record = atproto.find_record(did, REQUEST_COLLECTION, REQUEST_RKEY)
    except atproto.OAuthError as exc:
        raise ApplicationError(str(exc)) from exc

    cache.set(key, record if record is not None else _NO_APPLICATION,
              APPLICATION_CACHE_TTL)
    return record


def application_created_at(record):
    """`createdAt` off an application record as a datetime, or None.

    None rather than a raise, and for the same reason `_to_application` shrugs
    at a bad date: a record with an unreadable timestamp is still an
    application, and losing it over a formatting detail would be losing a
    person who asked.
    """
    try:
        return _parse_timestamp(record.get("createdAt"), "createdAt")
    except (AttributeError, PushError):
        return None


def submit_application(user, note=""):
    """Write this member's application into their own PDS. Returns the record.

    Idempotent by construction: rkey `self` means `putRecord` upserts, so a
    double-click writes the same record twice rather than creating two
    applications. The caller decides whether re-applying is offered at all —
    the home page does not, once it can see one.

    The freshly written record is cached on the way out so the redirect that
    follows shows "pending" immediately, rather than the member watching an
    unchanged page for the length of the cache TTL and clicking again.
    """
    note = validate_note(note)

    record = {
        "$type": REQUEST_COLLECTION,
        "createdAt": datetime.now(dt_timezone.utc).isoformat().replace(
            "+00:00", "Z"
        ),
    }
    if note:
        record["note"] = note

    try:
        atproto.write_record(user, REQUEST_COLLECTION, REQUEST_RKEY, record)
    except atproto.NoSession as exc:
        raise ApplicationError(
            "This account has no connection to a PDS, so there is nothing to "
            "write an application to."
        ) from exc
    except atproto.OAuthError as exc:
        log.warning("application write failed for %s: %s", user.did, exc)
        raise ApplicationError(
            "Your PDS would not accept the application. Signing in again may "
            "fix it."
        ) from exc

    cache.set(_application_cache_key(user.did), record, APPLICATION_CACHE_TTL)
    return record


# --- The registry, as something Corliss talks to ---------------------------
#
# `MembershipRegistry` is HappyView from this side: the service that holds the
# grant and revocation records, and the only place membership may be read from.
# It lives in this module rather than one of its own because everything the
# relationship needs is already here — the envelope parser, the roster read,
# `reconcile` itself — and splitting the transport out would put half of one
# relationship in each of two files.
#
# It reads through a service door (`syncMembers`) rather than the admin-session
# one the console uses, because the caller that matters most runs at boot with
# nobody signed in. That is the whole reason the door exists: a Corliss rebuilt
# from nothing must be able to re-derive membership without a human present.


class RegistryError(Exception):
    """The registry could not be reached, or answered with something unusable.

    Deliberately distinct from `ReconcileError` (the inputs cannot be trusted)
    and `PushError` (one record is malformed). Three different operator fixes:
    check the network and the token, check the roster, fix the record.
    """


SYNC_MEMBERS_NSID = "network.sharedcomputer.membership.syncMembers"
LIST_REQUESTS_NSID = "network.sharedcomputer.membership.listRequests"
APPROVE_MEMBER_NSID = "network.sharedcomputer.admin.approveMember"
REVOKE_MEMBER_NSID = "network.sharedcomputer.admin.revokeMember"
# Called with the *service* account's session, never an admin's — the space
# runtime accepts member changes only from the space authority. See
# `MembershipRegistry.set_space_access`.
SET_SPACE_ACCESS_NSID = "network.sharedcomputer.admin.setSpaceAccess"

# The tier vocabulary, mirroring `scn-member-registry/src/tiers.ts` and the
# TIERS table in `lua/approve_member.lua`. SCN owns these slugs; they are not
# read from whatever enforces entitlements, which is the point — the registry
# decides what a tier is, and the enforcer maps from the slug.
#
# Slugs rather than integers because `level-0` is the free tier and the most
# common one. The reason is stated upstream in JavaScript terms (`0` is falsy,
# so `if (grant.tier)` drops exactly the members it matters most for) and it
# survives the trip to Python unchanged: `if row.tier` is the same bug here.
#
# Copied rather than fetched, deliberately. The list is a decision, not data,
# and a registry outage must not leave Corliss unable to name a tier.
TIERS = tuple(f"level-{n}" for n in range(10))
DEFAULT_TIER = "level-0"

# The revocation lexicon's cap on `reason`.
REASON_MAX_CHARS = 300

REGISTRY_TIMEOUT = 30

# What one page of applications asks for, and how many pages are worth
# following. The Lua caps `limit` at 100 itself, so asking for more is asking
# for 100. The page cap is a guard against a cursor that never clears rather
# than a real expectation: at 500 applications the console needs a different
# design anyway, and the list says when it stopped early.
APPLICATIONS_PAGE_SIZE = 100
APPLICATIONS_MAX_PAGES = 5


# --- The registry as an OAuth party ----------------------------------------
#
# To *write* to the registry an admin needs a HappyView session, and getting one
# has a constraint that decides the shape of Corliss's whole login path:
#
# **HappyView provisions the DPoP key itself.** `POST /oauth/dpop-keys` returns
# a private JWK, and a client is expected to run its atproto handshake with that
# key before handing the resulting tokens back at `POST /oauth/sessions`.
# HappyView holds the key so it can prove possession to the PDS on the member's
# behalf.
#
# The consequence: **Corliss cannot register a session from tokens it already
# has.** An ordinary login binds its tokens to the ephemeral key
# `atproto.generate_key()` mints per flow, which HappyView has never seen and
# cannot use. Whoever does the handshake has to already be using HappyView's
# key — which is why `views.login` asks the roster *before* PAR and provisions
# from here when the answer is yes. See that function for why deciding on an
# unverified DID is safe.
#
# Corliss is a **public** client here, exactly as the SPA is: a client key and
# a PKCE verifier binding the provision to the registration, no client secret.
# Nothing needs one — the pair is single-use and short-lived — and not minting
# a secret keeps this repo's answer to "what can this key do if it leaks" the
# same as scn-member-registry's: register a session for someone who has already
# authorised, which still cannot write anything the roster does not allow.


def provision_registry_key(registry, *, pkce_challenge):
    """Ask HappyView for a DPoP keypair. Returns `(provision_id, private_key)`.

    The key comes back as a private JWK and leaves here as a `cryptography` EC
    key, so callers hold the same type `atproto.generate_key()` returns and
    nothing downstream needs to know where it came from.

    Raises `RegistryError`. Callers on the login path must treat that as
    "no approve powers this session", never as a failed login: HappyView being
    unreachable means no approvals, which is a documented consequence, and must
    not escalate into nobody being able to sign in.
    """
    if not registry.url or not registry.client_key:
        raise RegistryError(
            "registry is not configured for sessions: MEMBERSHIP_REGISTRY_URL "
            "and MEMBERSHIP_REGISTRY_CLIENT_KEY must both be set"
        )
    payload = registry._post(
        "/oauth/dpop-keys", {"pkce_challenge": pkce_challenge}
    )
    provision_id = payload.get("provision_id")
    jwk = payload.get("dpop_key")
    if not provision_id or not isinstance(jwk, dict):
        raise RegistryError("registry did not return a DPoP key provision")
    try:
        # PyJWT is already a dependency and already parses JWKs for the OIDC
        # half; no second key library for one conversion.
        key = ECAlgorithm.from_jwk(json.dumps(jwk))
    except (ValueError, TypeError, InvalidKeyError) as exc:
        raise RegistryError(f"registry returned an unusable DPoP key: {exc}") from exc
    if not isinstance(key, ec.EllipticCurvePrivateKey):
        # A public key would leave the session unable to sign anything, and the
        # failure would surface much later as an unexplained 401.
        raise RegistryError("registry returned a public DPoP key, not a private one")
    return provision_id, key


def register_registry_session(
    registry,
    *,
    provision_id,
    pkce_verifier,
    did,
    token_data,
    pds_url,
    issuer,
    scopes,
):
    """Hand the freshly-exchanged tokens to HappyView as a session for `did`.

    After this the admin can call procedures: HappyView resolves the bearer to
    `did`, the Lua reads that as `caller_did`, and the runtime stamps it as the
    author of whatever gets written.

    Raises `RegistryError`, which on the login path is not fatal — see
    `provision_registry_key`.
    """
    payload = {
        "provision_id": provision_id,
        "pkce_verifier": pkce_verifier,
        "did": did,
        "access_token": token_data.get("access_token", ""),
        "refresh_token": token_data.get("refresh_token", ""),
        "scopes": scopes,
        "pds_url": pds_url,
        "issuer": issuer,
    }
    result = registry._post("/oauth/sessions", payload)
    if result.get("did") != did:
        raise RegistryError(
            f"registry registered a session for {result.get('did')!r}, not {did!r}"
        )
    return result


class MembershipRegistry:
    """The SCN registry, as a thing Corliss reads membership out of.

        registry = MembershipRegistry.from_settings()
        report = registry.reconcile(dry_run=True)

    Constructed with its configuration rather than reaching for `settings`
    inside every method, so a test can point it anywhere and never touch the
    network.
    """

    __slots__ = ("url", "client_key", "token", "host")

    def __init__(self, url, client_key, token, host=""):
        self.url = (url or "").rstrip("/")
        self.client_key = client_key or ""
        self.token = token or ""
        # The Host header to present, when it differs from the URL's authority.
        # See `fetch_events` — this is what makes the internal address usable.
        self.host = host or ""

    @classmethod
    def from_settings(cls):
        return cls(
            settings.MEMBERSHIP_REGISTRY_URL,
            settings.MEMBERSHIP_REGISTRY_CLIENT_KEY,
            settings.MEMBERSHIP_REGISTRY_TOKEN,
            settings.MEMBERSHIP_REGISTRY_HOST,
        )

    @property
    def is_configured(self):
        """The url and the token. Asked before offering to run, so an
        unconfigured deployment shows a reason rather than a traceback.

        The client key is deliberately **not** required. Verified against
        production 2026-08-18: HappyView dispatches to a Lua script with no
        session and no client key at all — a bare XRPC call reaches `handle()`
        and gets the script's own error back. So the key adds nothing the token
        does not already carry here.

        That is not a micro-optimisation. The key is the *console's*
        origin-bound key, and requiring it would mean a cluster rebuilt before
        `zai-set-console client_key` had been run could not reconcile — tying
        the recovery path to the console being configured, when the whole point
        of this path is that it works when nothing else does.
        """
        return bool(self.url and self.token)

    def _query(self, nsid, params=None):
        """Call one XRPC *query* on the registry and return its JSON object.

        Every read Corliss makes of HappyView goes through here, so the two
        things that make reaching it at an internal address work — the `Host`
        header and the client key — are written once rather than per caller.
        """
        # Sent when we have one, omitted when we don't — see `is_configured`.
        # Harmless either way, and not something the call depends on.
        headers = {"x-client-key": self.client_key} if self.client_key else {}

        # The registry routes by virtual host, so reaching it at its internal
        # address needs the public name presented explicitly: a request whose
        # Host is a bare `10.1.1.x:3000` is refused with HTTP 421 "Unknown host"
        # before any routing happens. The edge normally supplies this — Caddy
        # preserves the original Host when it proxies — which is exactly why the
        # bypass has to do it by hand. Blank means "use the URL's own authority",
        # which is what a deployment pointed at the public origin wants.
        if self.host:
            headers["Host"] = self.host

        try:
            response = requests.get(
                f"{self.url}/xrpc/{nsid}",
                params=params or {},
                headers=headers,
                timeout=REGISTRY_TIMEOUT,
            )
        except requests.RequestException as exc:
            raise RegistryError(f"could not reach the registry: {exc}") from exc

        if response.status_code != 200:
            # The body carries the Lua's own error message ("forbidden: invalid
            # service token" and friends), which is the half an operator needs.
            raise RegistryError(
                f"registry returned HTTP {response.status_code}: "
                f"{response.text[:300]}"
            )

        try:
            payload = response.json()
        except ValueError as exc:
            raise RegistryError("registry response was not JSON") from exc
        if not isinstance(payload, dict):
            raise RegistryError("registry response was not a JSON object")
        return payload

    def _post(self, path, payload):
        """POST JSON to one of the registry's own (non-XRPC) endpoints.

        Its OAuth surface — `/oauth/dpop-keys`, `/oauth/sessions` — rather than
        `/xrpc/...`. Unauthenticated in the DPoP sense: there is no session yet,
        which is what these calls exist to create. The client key is what
        identifies the caller, and it is required here even though `_query` does
        without one.
        """
        try:
            response = requests.post(
                f"{self.url}{path}",
                json=payload,
                headers={"Content-Type": "application/json", **self._headers()},
                timeout=REGISTRY_TIMEOUT,
            )
        except requests.RequestException as exc:
            raise RegistryError(f"could not reach the registry: {exc}") from exc

        if not response.ok:
            raise RegistryError(
                f"registry returned HTTP {response.status_code} for {path}: "
                f"{response.text[:300]}"
            )
        try:
            body = response.json()
        except ValueError as exc:
            raise RegistryError(f"registry response to {path} was not JSON") from exc
        if not isinstance(body, dict):
            raise RegistryError(f"registry response to {path} was not an object")
        return body

    def public_url(self, path):
        """The URL the registry believes it is serving, for `path`.

        **Not where the request goes** — that is `self.url`, the internal
        address. This is the name a DPoP proof has to claim, and the two differ
        for exactly the reason `MEMBERSHIP_REGISTRY_HOST` exists at all: the
        registry routes by virtual host, so Corliss dials a private address and
        presents the public name, and the registry then reconstructs the request
        URI from that header. A proof signed for the address we dialled is
        refused with `DPoP proof htu mismatch` — the same internal-address-with-
        a-public-name trap that HTTP 421 was, one layer up.

        HTTPS unless the host says otherwise, because the public origin is
        behind the edge's TLS and that is the origin the registry knows itself
        by — the SPA reaches it there and its proofs are accepted. A deployment
        whose registry is genuinely plain HTTP can say so by putting the scheme
        in the host value.
        """
        if not self.host:
            return f"{self.url}{path}"
        origin = self.host if "://" in self.host else f"https://{self.host}"
        return f"{origin.rstrip('/')}{path}"

    def _headers(self):
        """The two headers every call to the registry carries.

        `Host` is what makes the internal address usable at all — see `_query`.
        The client key identifies which registry client is calling; a query does
        not need it, and a procedure does.
        """
        headers = {}
        if self.client_key:
            headers["x-client-key"] = self.client_key
        if self.host:
            headers["Host"] = self.host
        return headers

    def _procedure(self, nsid, payload, *, token):
        """Call one XRPC *procedure* on the registry, as the admin who owns
        `token`. Returns its JSON object.

        The authenticated sibling of `_query`, and the asymmetry between them is
        the whole architecture in miniature. A query dispatches with no session
        at all, which is why every read script begins by checking `caller_did`
        itself. A procedure never reaches the script without DPoP
        authentication — HappyView refuses it with "XRPC procedures require
        DPoP authentication" first — and that refusal is exactly what makes a
        write safe to expose: no shared token can produce a proof, so no shared
        token can ever author a grant.

        What authenticates here is the **admin's own** session: their access
        token as the bearer, and a proof signed by the DPoP key HappyView
        provisioned for them at login. `caller_did` follows from that, the Lua
        checks it against the roster, and the runtime stamps it as the record's
        author. There is deliberately no way to call this as Corliss itself.
        """
        if not self.url:
            raise RegistryError(
                "registry is not configured: MEMBERSHIP_REGISTRY_URL must be set"
            )
        if not self.client_key:
            # Unlike a query, which works without one. Said plainly because the
            # fix is a deployment step (`zai-set-console client_key`), not a bug.
            raise RegistryError(
                "registry is not configured for writes: "
                "MEMBERSHIP_REGISTRY_CLIENT_KEY must be set"
            )

        dpop_key = atproto.key_from_pem(token.dpop_private_pem)
        try:
            response, nonce = atproto.post_json_with_dpop(
                f"{self.url}/xrpc/{nsid}",
                payload,
                token.access_token,
                dpop_key,
                nonce=token.dpop_nonce or None,
                headers=self._headers(),
                # Signed for the public name, sent to the private address.
                htu=self.public_url(f"/xrpc/{nsid}"),
                timeout=REGISTRY_TIMEOUT,
            )
        except requests.RequestException as exc:
            raise RegistryError(f"could not reach the registry: {exc}") from exc

        if nonce and nonce != token.dpop_nonce:
            token.dpop_nonce = nonce
            token.save(update_fields=["dpop_nonce", "updated_at"])

        if response.status_code != 200:
            # A Lua `error()` comes back as HTTP 500 with the script's own text
            # ("forbidden: caller is not a current admin"), which is the half an
            # operator — or an admin who has just been removed from the roster —
            # actually needs to read.
            raise RegistryError(
                f"registry returned HTTP {response.status_code}: "
                f"{response.text[:300]}"
            )

        try:
            payload = response.json()
        except ValueError as exc:
            raise RegistryError("registry response was not JSON") from exc
        if not isinstance(payload, dict):
            raise RegistryError("registry response was not a JSON object")
        return payload

    def approve(self, token, did, tier):
        """Grant membership at `tier`, authored by the admin behind `token`.

        **Also how a tier change is made.** Re-approving writes a fresh grant
        and latest-event-wins resolves it; no record is ever edited, and the old
        grant stays in the space as the history of what was decided when. So
        there is no `change_tier` here and there should not be one — it would be
        a second name for this call and would imply an edit that never happens.

        Approving twice is harmless for the same reason, which matters because
        the push that clears the row from the queue is asynchronous and an admin
        may well click again before it lands.
        """
        if tier not in TIERS:
            # Refused here as well as in the Lua. A tierless or unknown grant is
            # a fail-open bug rather than a harmless default — a consumer that
            # turns it into an empty group claim makes Open WebUI remove
            # nothing, so the member silently keeps the tier they had.
            raise RegistryError(f"not a tier this network issues: {tier!r}")
        return self._procedure(
            APPROVE_MEMBER_NSID, {"did": did, "tier": tier}, token=token
        )

    def revoke(self, token, did, reason=""):
        """End membership, authored by the admin behind `token`.

        A revocation is a **new record**, never a deletion: the space is
        append-only, so what this writes is the event "access ended here", and
        the grant it answers stays exactly where it was. A member is active iff
        there is a grant with no later revocation.
        """
        payload = {"did": did}
        reason = (reason or "").strip()
        if reason:
            payload["reason"] = reason[:REASON_MAX_CHARS]
        return self._procedure(REVOKE_MEMBER_NSID, payload, token=token)

    def set_space_access(self, token, did, access):
        """Grant or remove registry space write access for an admin.

        Space membership is what makes a grant authoritative — an admin without
        it is on the roster and still cannot approve anyone — so this is the
        second half of a roster edit, not an optional extra.

        **`token` must be the service account's.** The space runtime accepts
        member changes only from the space authority, which is the service DID;
        an ordinary admin's session is refused however current they are. That is
        the reverse of `approve`/`revoke`, where the acting admin's own session
        is exactly what must be used, and the asymmetry is the registry's, not
        a choice made here.

        Idempotent both ways in the Lua, so retrying a partial roster edit is
        safe and is the documented recovery.
        """
        if access not in ("write", "none"):
            raise RegistryError(f"not a space access level: {access!r}")
        return self._procedure(
            SET_SPACE_ACCESS_NSID, {"did": did, "access": access}, token=token
        )

    def fetch_events(self):
        """Every grant and revocation in the registry space, push-shaped.

        The registry returns `{rkey, authorDid, record}` — the space metadata
        wrapped around the record, with no `did` and no `event`. Both are
        recoverable without guessing: `event` is which array the entry arrived
        in, and `did` is the leading half of the rkey. Filling them in here is
        what lets the push and the read share one parser, which is the only
        reason there is no second schema to drift from the lexicon.
        """
        if not self.is_configured:
            raise RegistryError(
                "registry is not configured: MEMBERSHIP_REGISTRY_URL and "
                "MEMBERSHIP_REGISTRY_TOKEN must both be set"
            )

        # The token travels as a query parameter, not a POST body, because
        # `syncMembers` has to be an XRPC *query*: HappyView refuses every
        # procedure call with "XRPC procedures require DPoP authentication"
        # before the script ever runs, and a service holding only a shared
        # token cannot produce a DPoP proof. Queries have no such gate.
        #
        # So the token is in the URL, and therefore in access logs. That is why
        # `MEMBERSHIP_REGISTRY_URL` should be the registry's *internal*
        # address: the request never reaches an edge or CDN, and the only log
        # it lands in belongs to a host whose root is already the trust
        # boundary.
        payload = self._query(SYNC_MEMBERS_NSID, {"token": self.token})

        events = []
        for key, event in (("grants", GRANT), ("revocations", REVOKE)):
            entries = payload.get(key)
            if not isinstance(entries, list):
                raise RegistryError(f"registry response has no {key!r} array")
            for entry in entries:
                events.append(self._to_envelope(entry, event))
        return events

    def fetch_applications(self):
        """Everyone who has asked to join, newest first. An `ApplicationList`.

        Reads the index, which is correct **only** for this collection — see
        the "Applications" section above for why that is not a hole in the
        never-read-grants-from-the-index rule.

        Needs the URL, and deliberately not `is_configured`: that also demands
        `MEMBERSHIP_REGISTRY_TOKEN`, which buys nothing here. `listRequests` is
        a query over records that are public in their authors' own repos, so it
        takes no credential at all — verified against production. Tying this
        panel to the reconcile token would hide the queue on a deployment that
        simply has not been given a token it does not need.
        """
        if not self.url:
            raise RegistryError(
                "registry is not configured: MEMBERSHIP_REGISTRY_URL must be set"
            )

        applications, unreadable, cursor, truncated = [], 0, None, False
        for _ in range(APPLICATIONS_MAX_PAGES):
            params = {"limit": APPLICATIONS_PAGE_SIZE}
            if cursor:
                params["cursor"] = cursor
            payload = self._query(LIST_REQUESTS_NSID, params)

            entries = payload.get("requests")
            if not isinstance(entries, list):
                raise RegistryError("registry response has no 'requests' array")

            for entry in entries:
                application = self._to_application(entry)
                if application is None:
                    # Counted, never dropped quietly: a record we cannot read
                    # is a person who asked and would otherwise be invisible.
                    unreadable += 1
                else:
                    applications.append(application)

            cursor = payload.get("cursor")
            if not isinstance(cursor, str) or not cursor:
                break
        else:
            # The loop ran out of pages with a cursor still in hand. Say so
            # rather than presenting a prefix as the whole queue.
            truncated = True

        return ApplicationList(applications, unreadable, truncated)

    @staticmethod
    def _to_application(entry):
        """One indexed `membership.request` row, or None if it cannot be read.

        The index returns the record's fields flat, with the `uri` alongside —
        so the applicant's DID is the repo half of that uri and nothing else.
        A row without a readable uri names nobody, which is the one field with
        no sensible fallback; `createdAt` and `note` each degrade to blank.
        """
        if not isinstance(entry, dict):
            return None
        try:
            did = did_from_uri(entry.get("uri"))
        except PushError:
            return None

        try:
            created_at = _parse_timestamp(entry.get("createdAt"), "createdAt")
        except PushError:
            # A missing or malformed date is not worth losing the applicant
            # over: the console renders an em-dash and the row keeps its place
            # in the order the registry returned it.
            created_at = None

        note = entry.get("note")
        return Application(did, created_at, note if isinstance(note, str) else "")

    @staticmethod
    def _to_envelope(entry, event):
        """One space record, in the shape `parse` already understands.

        A malformed entry is not repaired and not dropped: it is passed through
        with whatever it had, so `reconcile` reports it as unresolved. Silently
        discarding it here would hide a member behind a clean-looking report,
        which is the one failure the whole exercise exists to prevent.
        """
        if not isinstance(entry, dict):
            return {"event": event, "record": {}}

        rkey = entry.get("rkey")
        envelope = {
            "event": event,
            "rkey": rkey,
            "authorDid": entry.get("authorDid"),
            "record": entry.get("record") or {},
        }
        if isinstance(rkey, str):
            try:
                envelope["did"] = did_of(rkey)
            except PushError:
                # Leave `did` absent; `_preview` refuses it and reports the
                # rkey. Better than inventing a subject for a record we cannot
                # read.
                pass
        return envelope

    def reconcile(self, *, dry_run=False):
        """Fetch, resolve, and apply. Returns a `ReconcileReport`.

        The single entry point for every trigger — the console button, the
        management command, and whatever schedules it later — so none of them
        can drift into reconciling differently from the others.

        `fetch_roster` is called directly, not through `is_cluster_admin`,
        precisely because it raises: a roster that could not be fetched would
        otherwise fail closed to "nobody is an admin", and every event would be
        discarded as unauthorised while the report claimed success.
        """
        events = self.fetch_events()
        roster = fetch_roster(refresh=True)
        if not roster.exists:
            # `fetch_roster` answers "absent" rather than raising so that the
            # service account can sign in and write the first one. Here that
            # answer is useless: with no roster every event is unauthorised, so
            # reconciling would empty the cache and report success.
            raise ReconcileError(
                "there is no admin roster record, so no grant can be attributed "
                "to a current admin. Add the first admin before reconciling."
            )
        # Resolves to the module-level function below/above, not this method —
        # the name is shadowed only inside the class body's namespace.
        return reconcile(events, roster, dry_run=dry_run)
