# Generated by Django 6.1 on 2026-08-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corliss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(db_index=True, max_length=255, unique=True)),
                ('active', models.BooleanField(help_text='Resolved membership: true after a grant, false after a revocation.')),
                ('tier', models.CharField(blank=True, help_text='SCN-owned tier slug (level-0 … level-9) from the most recent grant. Retained after revocation for audit — always check `active` too.', max_length=64)),
                ('last_rkey', models.CharField(max_length=600)),
                ('last_event_at', models.DateTimeField()),
                ('author_did', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'membership cache entries',
            },
        ),
    ]
