# Generated by Django 6.1 on 2026-08-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corliss', '0003_oidcsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='atprototoken',
            name='registry_session_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
